// App
export const APP_HANDLE_STATE = "APP_HANDLE_STATE";
export const APP_HANDLE_STATE_GLOBAL = "APP_HANDLE_STATE_GLOBAL";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
// Home
export const HOME_HANDLE_STATE = "HOME_HANDLE_STATE";
